"""Report generator - synthesizes agent outputs into markdown report."""

from datetime import datetime
from typing import Any

from .templates import (
    REPORT_TEMPLATE,
    format_companies_table,
)


def generate_report(
    query: str,
    companies: list[str],
    financial_data: dict | None,
    competitor_data: dict | None,
    llm: Any = None,
) -> str:
    """
    Generate a comprehensive research report from agent outputs.

    Args:
        query: Original user query
        companies: List of companies analyzed
        financial_data: Output from financial agent
        competitor_data: Output from competitor agent
        llm: LLM instance for synthesis (optional)

    Returns:
        Formatted markdown report.
    """
    # Extract responses from agent outputs
    financial_response = ""
    if financial_data and "response" in financial_data:
        financial_response = financial_data["response"]

    competitor_response = ""
    if competitor_data and "response" in competitor_data:
        competitor_response = competitor_data["response"]

    # If we have an LLM, use it to synthesize a proper report
    if llm is not None:
        return _generate_with_llm(
            query=query,
            companies=companies,
            financial_response=financial_response,
            competitor_response=competitor_response,
            llm=llm,
        )

    # Otherwise, create a basic structured report
    return _generate_basic_report(
        query=query,
        companies=companies,
        financial_response=financial_response,
        competitor_response=competitor_response,
    )


def _generate_with_llm(
    query: str,
    companies: list[str],
    financial_response: str,
    competitor_response: str,
    llm: Any,
) -> str:
    """Generate report using LLM to synthesize agent outputs."""

    synthesis_prompt = f"""You are synthesizing a research report from agent outputs.

Original Query: {query}

Companies Analyzed: {', '.join(companies)}

=== FINANCIAL AGENT OUTPUT ===
{financial_response}

=== COMPETITOR AGENT OUTPUT ===
{competitor_response}

=== INSTRUCTIONS ===
Create a comprehensive markdown research report with these sections:

1. **Executive Summary** (2-3 paragraphs)
   - Key findings from both financial and competitive analysis
   - Main takeaways for the reader

2. **Companies Analyzed** (table format)
   - Company name, ticker, primary products

3. **Financial Comparison** (table + analysis)
   - Market cap, revenue, growth rates, margins
   - Include a comparison table
   - Brief analysis of financial health trends

4. **Competitive Analysis**
   - Product offerings comparison
   - Market positioning
   - Strengths and weaknesses for each company
   - Key differentiators

5. **Key Insights** (numbered list)
   - 3-5 actionable insights from the research

6. **Sources**
   - List all sources mentioned in agent outputs

Format the report in clean markdown. Use tables where appropriate.
Start with a title: "# Competitive Analysis: Observability Market"
Include the date: *Generated: {datetime.now().strftime('%Y-%m-%d')} | Research Agent v0.1*
"""

    response = llm.invoke([{"role": "user", "content": synthesis_prompt}])
    return response.content


def _generate_basic_report(
    query: str,
    companies: list[str],
    financial_response: str,
    competitor_response: str,
) -> str:
    """Generate a basic report without LLM synthesis."""

    date_str = datetime.now().strftime("%Y-%m-%d")

    report = f"""# Competitive Analysis: Observability Market
*Generated: {date_str} | Research Agent v0.1*

## Research Query
{query}

## Companies Analyzed

{format_companies_table(companies)}

## Financial Analysis

{financial_response if financial_response else "*Financial data not available*"}

## Competitive Analysis

{competitor_response if competitor_response else "*Competitive data not available*"}

## Sources

- Yahoo Finance (yfinance)
- Tavily Web Search

---
*This report was generated by the Research Agent Team.*
"""

    return report


def format_as_markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    """Format data as a markdown table."""
    if not headers or not rows:
        return ""

    # Header row
    table = "| " + " | ".join(headers) + " |\n"

    # Separator row
    table += "| " + " | ".join(["---"] * len(headers)) + " |\n"

    # Data rows
    for row in rows:
        table += "| " + " | ".join(str(cell) for cell in row) + " |\n"

    return table
