"""Report templates for research output."""

from datetime import datetime

REPORT_TEMPLATE = """# {title}
*Generated: {date} | Research Agent v0.1*

## Executive Summary

{executive_summary}

## Companies Analyzed

{companies_table}

## Financial Comparison

{financial_section}

## Competitive Analysis

{competitive_section}

## Key Insights

{key_insights}

## Sources

{sources}

---
*This report was generated by the Research Agent Team using data from Yahoo Finance and Tavily web search.*
"""


def get_report_template() -> str:
    """Get the report template with current date."""
    return REPORT_TEMPLATE


def format_companies_table(companies: list[str]) -> str:
    """Format companies into a markdown table."""
    if not companies:
        return "*No companies analyzed*"

    table = "| Company | Ticker | Primary Focus |\n"
    table += "|---------|--------|---------------|\n"

    # Map companies to their info
    company_info = {
        "cisco": ("CSCO", "Splunk O11y, AppDynamics"),
        "splunk": ("CSCO", "Splunk Observability Cloud"),
        "appdynamics": ("CSCO", "APM, Business Observability"),
        "datadog": ("DDOG", "Cloud Monitoring, APM, Logs"),
        "dynatrace": ("DT", "AI-powered Observability"),
    }

    for company in companies:
        name_lower = company.lower()
        for key, (ticker, focus) in company_info.items():
            if key in name_lower:
                table += f"| {company} | {ticker} | {focus} |\n"
                break
        else:
            table += f"| {company} | - | - |\n"

    return table


def format_financial_table(financial_data: dict | None) -> str:
    """Format financial data into a markdown table."""
    if not financial_data:
        return "*Financial data not available*"

    response = financial_data.get("response", "")

    # If the response contains structured data, format it
    # Otherwise return the raw response
    if isinstance(response, str) and len(response) > 0:
        return response

    return "*Financial data not available*"


def format_source_list(sources: list[str]) -> str:
    """Format sources into a numbered list."""
    if not sources:
        return "- Yahoo Finance\n- Tavily Web Search"

    result = ""
    for i, source in enumerate(sources, 1):
        result += f"- [{i}] {source}\n"

    return result
